services:
  mongo:
    image: mongo:6.0
    container_name: notes-mongo
    profiles: ['prod']
    hostname: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./mongodata:/data/db
  bot:
    image: notes-bot
    container_name: notes-bot
    profiles: ['prod']
    restart: unless-stopped
    env_file:
      - ../docker.env
  mongodb-dev:
    image: mongo:6.0
    container_name: notes-mongo-dev
    profiles: ['dev']
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ../mongodata:/data/db
  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: notes-mongo-express
    hostname: express
    restart: unless-stopped
    profiles: ['dev']
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASS}@mongo:27017/
